---
- name: ansible-clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: 1.11.0

- name: vector-role
  src: git@github.com:ra-leonid/vector-role.git
  scm: git
  version: 1.0.8

- name: lighthouse-role
  src: git@github.com:ra-leonid/lighthouse-role.git
  scm: git
  version: 1.0.4