---
- name: Install ansible-clickhouse role
  hosts: clickhouse
  roles:
    - ansible-clickhouse
  post_tasks:
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
    - name: Create table
      ansible.builtin.command: "clickhouse-client -q 'create table logs.somelog ({{ file_log_structure }}) ENGINE = Log();'"
      register: create_tbl
      failed_when: create_tbl.rc != 0 and create_tbl.rc != 57
      changed_when: create_tbl.rc == 0

- name: Install Vector
  hosts: vector
  roles:
    - vector-role

- name: Install LightHouse
  hosts: lighthouse
  roles:
    - lighthouse-role
