---
clickhouse_version: 'latest'

clickhouse_listen_host:
  - "::"

clickhouse_dbs_custom:
  - { name: logs }

clickhouse_profiles_custom:
 default:
   date_time_input_format: best_effort

clickhouse_users_custom:
  - { name: "logger",
      password: "logger",
      networks: { "::" },
      profile: "default",
      quota: "default",
      access_management: 0 }

file_log_structure: "'file' String, 'hosts' String, 'message' String, 'timestamp' DateTime"